using System;

namespace Age;
{
   Class Program
   {
       Static Void Main(String[] args)
       {
        Console.WriteLine("Your Age: ")
        Int Age = (Convert.ToInt32(Console.ReadLine())
        Console.Write("Your Age is " + Age)

        If (Age >= 18)
       {
        Console.WriteLine("You got accepted!")
       }
        Else if (Age <= 18)
       {
        Console.WriteLine("You need to Be 18 Years old or older")
       }
   }
}
